### ISSUE TITLE
Cannot copy stacks to clipboard

### ISSUE THREAD

**Issue by yuealice** [Infiziert90/MOActionPlugin#31]
![image](https://user-images.githubusercontent.com/92181288/136622744-b526d412-6634-4d98-adca-aad06ddf3d84.png)
This error pops up whenever I try and the plugin just stops working until I restart my game. Nothing is copied to my clipboard either.

**Comment by Rueby** [comment]
I've encountered the same issue when I tried to copy my stacks to share with my friend.

**Comment by alexwh** [comment]
Traceback from when this happens:
```
2021-10-09 12:45:59.945 +01:00 [ERR] [MOAction] UiBuilder OnBuildUi caught exception
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at MOAction.Configuration.MoActionStack.Equals(ConfigurationEntry c)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at MOAction.MOActionPlugin.CopyToClipboard(List`1 list)
   at MOAction.MOActionPlugin.DrawConfig()
   at Dalamud.Interface.UiBuilder.OnDraw() in C:\goatsoft\companysecrets\dalamud\Interface\UiBuilder.cs:line 287
```

**Comment by Infiziert90** [comment]
Closing this, if the issue still exists in newer version please reopen the issue
